spring:
  application:
    name: PaymentService
  datasource:
    url: jdbc:postgresql://localhost:5430/payment
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


paypal:
  client-id: your-client-id
  client-secret: your-client-secret
  mode: sandbox
